# Generated by Django 4.1 on 2022-08-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcellmodel',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
