# Generated by Django 4.0.4 on 2022-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
