# Generated by Django 4.1 on 2022-10-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcellmodel',
            name='owner_user',
        ),
        migrations.AlterField(
            model_name='profileusermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='shopcellmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/smartphone/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='shopcellmodel',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopcell', to='cells.profileusermodel'),
        ),
    ]
