# Generated by Django 4.0.4 on 2022-06-04 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0002_profileuser_key_date_profileuser_key_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='key_date',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='key_token',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
