# Generated by Django 4.0.4 on 2022-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_remove_profileuser_key_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcell',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shopingcell',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
