# Generated by Django 4.0.4 on 2022-06-05 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0004_alter_shopingcell_model_name_alter_shopingcell_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcell',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shopingcell',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopingcell', to=settings.AUTH_USER_MODEL),
        ),
    ]
