# Generated by Django 4.0.4 on 2022-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_alter_profileusermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
