# Generated by Django 4.0.4 on 2022-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0005_alter_shopingcell_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcell',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
