# Generated by Django 4.0.4 on 2022-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0006_alter_shopingcellmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='model_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
