# Generated by Django 4.0.4 on 2022-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0007_profileuser_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcell',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
