# Generated by Django 4.0.4 on 2022-07-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0007_alter_shopingcellmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='price',
            field=models.FloatField(max_length=6),
        ),
    ]
