# Generated by Django 4.0.4 on 2022-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0008_alter_shopingcellmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusermodel',
            name='phone',
            field=models.CharField(max_length=8),
        ),
    ]
