# Generated by Django 4.0.4 on 2022-06-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0008_alter_shopingcell_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcell',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shopingcell',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
