# Generated by Django 4.0.4 on 2022-06-25 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0009_alter_shopingcell_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUser',
            new_name='ProfileUserModel',
        ),
        migrations.RenameModel(
            old_name='ShopingCell',
            new_name='ShopingCellModel',
        ),
    ]
