# Generated by Django 4.0.4 on 2022-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0009_alter_profileusermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='smartphone/%Y/%m/%d'),
        ),
    ]
