# Generated by Django 4.0.4 on 2022-07-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0010_rename_profileuser_profileusermodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopingcellmodel',
            old_name='desciption',
            new_name='description',
        ),
    ]
