# Generated by Django 4.0.4 on 2022-07-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0011_rename_desciption_shopingcellmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusermodel',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileusermodel',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='model_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shopingcellmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
