# Generated by Django 4.0.4 on 2022-07-02 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0012_alter_profileusermodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingcellmodel',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cells.profileusermodel'),
        ),
    ]
